// This file is generated by FireStudio.

'use server';

/**
 * @fileOverview A flow to extract expense information from an image of a receipt.
 *
 * - extractExpenseFromImage - A function that extracts expense details from an image.
 * - ExtractExpenseFromImageInput - The input type for the extractExpenseFromImage function.
 * - ExtractExpenseFromImageOutput - The return type for the extractExpenseFromImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { zfd } from 'zod-form-data';

const ExtractExpenseFromImageInputSchema = zfd.formData({
  receipt: zfd.file(z.instanceof(File)),
});
export type ExtractExpenseFromImageInput = z.infer<typeof ExtractExpenseFromImageInputSchema>;


const SuggestedCategorySchema = z.enum(['Food', 'Transport', 'Clothing', 'Home', 'Other']);

const ExtractExpenseFromImageOutputSchema = z.object({
  amount: z.number().describe('The total amount of the expense.'),
  category: SuggestedCategorySchema.optional().describe('The suggested category for the expense.'),
  note: z.string().describe('A brief note describing the expense, usually the merchant name.'),
  date: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/)
    .describe('The date of the expense in YYYY-MM-DD format.'),
});

export type ExtractExpenseFromImageOutput = z.infer<typeof ExtractExpenseFromImageOutputSchema>;

// Converts a File to a data URI
async function fileToDataUri(file: File): Promise<string> {
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    return `data:${file.type};base64,${buffer.toString('base64')}`;
}


export async function extractExpenseFromImage(
  input: ExtractExpenseFromImageInput
): Promise<ExtractExpenseFromImageOutput> {
  const dataUri = await fileToDataUri(input.receipt);
  return extractExpenseFromImageFlow({ dataUri, contentType: input.receipt.type });
}

const flowInputSchema = z.object({
    dataUri: z.string(),
    contentType: z.string(),
});

const prompt = ai.definePrompt({
  name: 'extractExpenseFromImagePrompt',
  input: {schema: flowInputSchema},
  output: {schema: ExtractExpenseFromImageOutputSchema},
  prompt: `You are an expert receipt reader. Analyze the receipt image provided and extract the following information:
- The total amount of the expense.
- The date of the expense (in YYYY-MM-DD format). If the year is not present, assume the current year.
- A brief note, which should be the merchant's name.
- A suggested expense category from the following options: Food, Transport, Clothing, Home, Other.

Receipt Image: {{media url=dataUri contentType=contentType}}

Output the extracted information as a JSON object that conforms to the specified output schema.
{{{outputSchemaDescription}}}`,
});

const extractExpenseFromImageFlow = ai.defineFlow(
  {
    name: 'extractExpenseFromImageFlow',
    inputSchema: flowInputSchema,
    outputSchema: ExtractExpenseFromImageOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
