// This file is generated by FireStudio.

'use server';

/**
 * @fileOverview A flow to generate personalized savings tips based on user spending habits and budget.
 *
 * - generatePersonalizedSavingsTips - A function that generates personalized savings tips.
 * - GeneratePersonalizedSavingsTipsInput - The input type for the generatePersonalizedSavingsTips function.
 * - GeneratePersonalizedSavingsTipsOutput - The return type for the generatePersonalizedSavingsTips function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePersonalizedSavingsTipsInputSchema = z.object({
  userId: z.string().describe('The ID of the user.'),
  totalSpentThisMonth: z
    .number()
    .describe('The total amount spent by the user this month.'),
  monthlyBudgetLimit: z
    .number()
    .describe('The user’s monthly budget limit.'),
  expensesByCategory: z.record(
    z.string(),
    z.number()
  ).describe('The user’s expenses grouped by category.'),
  previousMonthTotalSpent: z
    .number()
    .describe('The total amount spent by the user last month.'),
  language: z.string().describe('The language for the response (e.g., "en" or "es").'),
});

export type GeneratePersonalizedSavingsTipsInput = z.infer<typeof GeneratePersonalizedSavingsTipsInputSchema>;

const GeneratePersonalizedSavingsTipsOutputSchema = z.object({
  alerts: z.array(z.string()).describe('A list of alerts for the user.'),
  recommendations: z
    .array(z.string())
    .describe('A list of recommendations for the user.'),
});

export type GeneratePersonalizedSavingsTipsOutput = z.infer<typeof GeneratePersonalizedSavingsTipsOutputSchema>;

export async function generatePersonalizedSavingsTips(
  input: GeneratePersonalizedSavingsTipsInput
): Promise<GeneratePersonalizedSavingsTipsOutput> {
  return generatePersonalizedSavingsTipsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePersonalizedSavingsTipsPrompt',
  input: {schema: GeneratePersonalizedSavingsTipsInputSchema},
  output: {schema: GeneratePersonalizedSavingsTipsOutputSchema},
  prompt: `You are a personal finance advisor. Analyze the user's spending habits and budget to provide personalized savings tips in the specified language.

Language for response: {{{language}}}

Here's the user's financial information:
- User ID: {{{userId}}}
- Total Spent This Month: {{{totalSpentThisMonth}}}
- Monthly Budget Limit: {{{monthlyBudgetLimit}}}
- Expenses By Category:
{{#each expensesByCategory}}
  - {{@key}}: {{{this}}}
{{/each}}
- Previous Month Total Spent: {{{previousMonthTotalSpent}}}

Analyze the data and provide:
1. A list of alerts if any category exceeds 30% of the budget or if the projected monthly spending exceeds the budget.
2. Recommendations on how to adjust spending, comparing with previous months.

Output the alerts and recommendations as a JSON object, ensuring all text is in the requested language ({{{language}}}).

Remember that the output should conform to this schema:
{{{outputSchemaDescription}}}`,
});

const generatePersonalizedSavingsTipsFlow = ai.defineFlow(
  {
    name: 'generatePersonalizedSavingsTipsFlow',
    inputSchema: GeneratePersonalizedSavingsTipsInputSchema,
    outputSchema: GeneratePersonalizedSavingsTipsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
